### ISSUE TITLE
Testing Rust + Emscripten

### ISSUE THREAD

**Issue by zackradisic** [zackradisic/cheatsheets#23]
```bash
CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUNNER=node cargo test --target wasm32-unknown-emscripten
```

Or you can change your `.cargo/config.toml` to also enable threads for node
```toml
[target.wasm32-unknown-emscripten]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory", "-C", "link-args=-pthread -s PTHREAD_POOL_SIZE=1"]
runner = ["node", "--experimental-wasm-threads", "--experimental-wasm-bulk-memory"]

```

If you edited your `.cargo/config.toml` for #21 then make sure to comment it out.
